### PR TITLE
Add detail about postscriptSlantAngle

### PR DESCRIPTION
**Pull request by benkiel**
From https://github.com/googlefonts/ufo2ft/issues/508#issuecomment-867022583

### CODE REVIEW

**Comment by benkiel** [comment]
closes #181

**Review by madig — APPROVED** [review]

**Review by moyogo — COMMENTED** [review]
Saying it "does not correspond to a field in the Type 1/CFF table" is incorrect, see https://github.com/googlefonts/ufo2ft/issues/508#issuecomment-867874999.
The FLS5 Font Info gives the following description for the Slant angle field: "Slant is based on FontMatrix and works only in T1".
When Type 1 fonts, like Win Type 1 for example, are generated with a Slant angle value in FLS5, the glyphs are slanted.

**Comment by moyogo** [comment]
The description should be changed to something like:
> Artificial slant angle. This must be an angle in counter-clockwise degrees from the vertical. This value is *not* the same as the italic angle. Font authoring tools may use this value to set the FontMatrix in Type 1/CFF table.

**Comment by benkiel** [comment]
@moyogo Agree, that's better. My "does not correspond" meant that there is _not_ a slant angle in the T1 or CFF spec, but your wording is more clear, thank you

**Comment by moyogo** [comment]
Thank you @benkiel

**Pull request merged**
