### PR TITLE
Document minor version for UFO and glyf

### LINKED ISSUE #78: Make formatVersion in metainfo.plist a major/minor
We have switched to an incremental approach to updating the spec rather than holding lots of changes until a major version bump. To make it easier for readers to more easily identify these new format UFOs we need to make the `formatVersion` in `metainfo.plist` a `float` instead of an `int`.

### PR DESCRIPTION
**Pull request by benkiel**
Closes #78. @anthrotype I believe I have captured what is happening in ufoLib, but please give a look.

### CODE REVIEW

**Comment by typesupply** [comment]
Should we bump the current minor version of UFO and GLIF to 1 with this change? This is a breaking change so it would be good to be able to pinpoint when it started.

**Comment by benkiel** [comment]
Yes, we should. I don't know where best to put that in the current site structure?

**Comment by alerque** [comment]
So it doesn't get lost in the shuffle, when 3.1 documentation has a home the change it #134 should also probably be included.

**Review by anthrotype — APPROVED** [review]

**Comment by typesupply** [comment]
@benkiel:

> Yes, we should. I don't know where best to put that in the current site structure?

Hm. I'll merge this and figure out where to add a note.

**Pull request merged**
